name: 'Trigger ChangeGuard Analysis'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: 'Trigger analysis workflow in ai-code-analyzer repo'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: pranjalwagh/ai-code-analyzer  # <-- Fixed: just owner/repo format
          event-type: run-analysis
          client-payload: >-
            {
              "commit": "${{ github.sha }}",
              "pr_number": "${{ github.event.pull_request.number }}",
              "repo_name": "${{ github.repository }}"
            }